Sw 5466 support velodyne point type in the ros driver
ouster-lidar/ouster-ros pull request #216
Opened 2023-09-13 19:08 UTC by Samahu

## Related Issues & PRs
- closes #15 
- closes #210 

## Summary of Changes
- Implement a mechanism to choose a different representation of the point cloud type 

## Validation
- TBD

2023-10-12 20:51 UTC, mtswisher requested changes
Just made some typo changes :)  How do you decide whether to designate a function as inline? I haven't seen the factory pattern in quite awhile so it was cool to see that solve this problem. Will probably need to dig into some more to really understand what is going on but LGTM :)

2023-10-12 20:51 UTC, mtswisher commented on ouster-ros/config/driver_params.yaml
> +     #  - xyzi: same as xyzi type but adds ring(channel) field.
xyzi should be xyzir on this line

2023-10-12 20:51 UTC, mtswisher commented on ouster-ros/include/ouster_ros/sensor_point_types.h
> + * 4. nea_ir
near_ir :D

2023-10-12 20:51 UTC, mtswisher commented on ouster-ros/include/ouster_ros/sensor_point_types.h
> + * The only Point_RNG15_RFL8_NIR8 aks LOW_DATA which does not omits the signal
aka as opposed to aks

2023-10-13 17:28 UTC, Samahu commented
> Just made some typo changes :)

Addressed!

> How do you decide whether to designate a function as inline?

Typically for short one liner methods this could minimally increase the code size but avoid having to invoke the method which is always faster .. With modern compilers the **inline** keyword only serves as a suggestion, compilers could inline methods automatically .. and could also ignore the suggestion if the method body is too long (in this case one needs to use **__forceinline**).  
 
> I haven't seen the factory pattern in quite awhile so it was cool to see that solve this problem. Will probably need to dig into some more to really understand what is going on but LGTM :)

Yeah, the factory pattern is definitely needed here. I will add more comments to the PR to explain what's going on and how could developers use existing code to implement other point types that are not included here.

2023-10-13 18:06 UTC, twslankard approved these changes

2023-11-13 19:36 UTC, merged